### ISSUE TITLE
Duplicate savedCar

### ISSUE THREAD

**Issue by Ultrafeel** [Apress/pro-c-sharp-9-w-.net-core-5#11]
```
Console.WriteLine("Original Car: {0}",savedCar.ToString());
Console.WriteLine("Read Car: {0}",savedCar.ToString());

```

**Comment by Ultrafeel** [comment]
Same in the sample code

**Comment by Ultrafeel** [comment]
Also there is a duplicate in the line  https://github.com/Apress/pro-c-sharp-9-w-.net-core-5/blob/2c7682d0e9ea130519b671b3ce1574a715d97cc6/SampleCode/Chapter_20/SimpleSerialize/Program.cs#L76

**Comment by skimedic** [comment]
Thank you for pointing that out. I have updated the code in the repo to the correct code and updated the errata.md with the details. Both of these were caught and corrected for the C# 10 version of the book.
