### ISSUE TITLE
Wrong chapter ref.

### ISSUE THREAD

**Issue by Ultrafeel** [Apress/pro-c-sharp-9-w-.net-core-5#12]
> Also recall from Chapter 9, the C# language allows you to use a similar syntax to initialize collections of objects. 

Seems to be 10

**Comment by skimedic** [comment]
You are correct. I've updated the errata and sent a message to the publishing team to correct it for the C# 10 book. It might not be able to be changed, but I have it in my notes to make sure it's corrected moving forward. Thank you.
