### ISSUE TITLE
Errata on page 940

### ISSUE THREAD

**Issue by hmundle** [Apress/pro-c-sharp-9-w-.net-core-5#14]
I was planning to do a pull request on this change, but it did not work out.

8< 8< 8< 8< 8< 8< 8< 8< 8< 8< 8< 8< 8< 8< 

Subject: [PATCH] Add correction for page 940, SingleOrDefault is always TOP(2)
 as far as I understood from reading.

---
 errata.md | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/errata.md b/errata.md
index a16085a..a5e841e 100644
--- a/errata.md
+++ b/errata.md
@@ -153,3 +153,12 @@ foreach (var c in savedJsonCars)
 }
 ```
 ***
+On **page 940** [incorrect SQL statement]:
+ 
+On page 940, for `SingleOrDefaultShouldReturnDefaultIfNoneMatch()` the LINQ query gets translated with `TOP(2)`. The statement should be this: 
+```SQL
+SELECT TOP(2) [c].[Id], [c].[TimeStamp], [c].[FirstName], [c].[FullName], [c].[LastName]
+FROM [Dbo].[Customers] AS [c]
+WHERE [c].[Id] = 10
+```
+***
--

**Comment by skimedic** [comment]
thank you for finding this. I've updated the errata. This was already corrected in the next edition.
