### ISSUE TITLE
Run AutoLot.Mvc and AutoLot.Api Together (page 1329)

### ISSUE THREAD

**Issue by pmarangoni** [Apress/pro-c-sharp-9-w-.net-core-5#15]
I'm not having luck running the two projects together.  I've configured Visual Studio to run both, but I get this error in the MVC browser (at https://localhost:5001/):

**An unhandled exception occurred while processing the request.**
UriFormatException: Invalid URI: Invalid port specified.
System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind, ref UriCreationOptions creationOptions)

The API browser opens with Swagger (at https://localhost:5021/swagger/index.html) just fine.

In the book, you suggest changing the ports in appsettings.development.json, but what values should they be changed to?

Any assistance will be very much appreciated!

**Comment by skimedic** [comment]
Look at page 1319:
Update the Application Configuration
The appsettings.Development.json file will add the service information for the local machine. Open the appsettings.Development.json file and update it to the
following:
{
"Logging": {
"MSSqlServer": {
"schema": "Logging",
"tableName": "SeriLogs",
"restrictedToMinimumLevel": "Warning"
}
},
"RebuildDataBase": false,
"ApplicationName": "AutoLot.Mvc - Dev",
"ConnectionStrings": {
"AutoLot": "Server=.,5433;Database=AutoLot;User ID=sa;Password=P@ssw0rd;"
},
"ApiServiceSettings": {
"Uri": "https://localhost:5021/",
"CarBaseUri": "api/Cars",
"MakeBaseUri": "api/Makes"
}
}
■■Note Make sure the port number matches your configuration for AutoLot.Api.
By utilizing the ASP.NET Core configuration system and updating the environment-specific files
(e.g., appsettings.staging.json and appsettings.production.json), your application will have the
appropriate values without having to change any code.

**Comment by pmarangoni** [comment]
I have already followed those instructions, although you don't specify **_which_** project's appsettings file to add those settings to.

Here is the appsettings.Development.json file from my **MVC** project:

```
{
  "Logging": {
    "MSSqlServer": {
      "TableName": "Serilogs",
      "Schema": "Logging",
      "ConnectionStringName": "AutoLot"
    },
    "File": {
      "Drive": "c",
      "FilePath": "temp",
      "FileName": "log_AutoLot.txt"
    },
    "General": {
      "RestrictToMinimumLevel": "Warning"
    }
  },
  "ConnectionStrings": {
    "AutoLot": "Data Source=PAUL-DESKTOP-AM;Initial Catalog=AutoLot;User ID=apress;Password=apress;Integrated Security=False;MultipleActiveResultSets=True"
  },
  "RebuildDatabase": false,
  "ApplicationName": "AutoLot.Mvc - Dev",
  "ApiServiceSettings": {
    "Uri": "https://localhost:5021",
    "CarBaseUri": "api/Cars",
    "MakeBaseUri": "api/Makes"
  }
}

```
Here is the launchSettings.json file from the API project:

```
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:65517",
      "sslPort": 44398
    }
  },
  "profiles": {
    "AutoLot.Api": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:5021;http://localhost:5020",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

Here is the appsettings.Development.json file from the API project:

```
{
  "Logging": {
    "MSSqlServer": {
      "TableName": "Serilogs",
      "Schema": "Logging",
      "ConnectionStringName": "AutoLot"
    },
    "File": {
      "Drive": "c",
      "FilePath": "temp",
      "FileName": "log_AutoLot.txt"
    },
    "General": {
      "RestrictToMinimumLevel": "Warning"
    }
  },
  "ConnectionStrings": {
    "AutoLot": "Data Source=PAUL-DESKTOP-AM;Initial Catalog=AutoLot;User ID=apress;Password=apress;Integrated Security=False;MultipleActiveResultSets=True"
  },
  "RebuildDatabase": false,
  "ApplicationName": "AutoLot.Api - Development"
}
```

**Comment by skimedic** [comment]
are you running under kestrel or IIS? If IIS, the port you are using is 44398 (https):
 "iisExpress": {
      "applicationUrl": "http://localhost:65517",
      "sslPort": 44398
    }

**Comment by pmarangoni** [comment]
I thought I was running with Kestrel. Anyway, I just tried changing the launchsettings.json file in the API project to the following, and still get that error.

```
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:5020",
      "sslPort": 5021
    }
  },
  "profiles": {
    "AutoLot.Api": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:5021;http://localhost:5020",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by pmarangoni** [comment]
<img width="649" alt="Screenshot 2022-09-10 153053" src="https://user-images.githubusercontent.com/10107978/189504008-9366a765-1a47-4a26-9cfb-3eef588b4715.png">

**Comment by skimedic** [comment]
did you compare your code to what's in the repo?

**Comment by pmarangoni** [comment]
I thought I did, but if you don't see any issue with the json files I've posted, I must have missed something.  I do appreciate you taking the time to try assisting.  I guess I will have to dig deeper.

**Comment by pmarangoni** [comment]
I get the same results when I run each project via PowerShell command prompt too (first running API project with dotnet watch run, then doing the same for the MVC project)

**Comment by skimedic** [comment]
that error page looks like you have a type in the appsettings.development.json file. Step through the code to see what values are being used to build the URI. If you have a typo in the JSON, the settings won't load.

**Comment by pmarangoni** [comment]
I finally figured it out...  I'm such a clod...

I added a try/catch around the code in the GetMakesAsync() method, as so:

```
public async Task<IList<Make>> GetMakesAsync()
		{
			try
			{
				var response = await _client.GetAsync($"{_settings.Uri}{_settings.MakeBaseUri}");
				response.EnsureSuccessStatusCode();
				var result = await response.Content.ReadFromJsonAsync<IList<Make>>();
				return result;
			}
			catch(Exception ex)
			{
				throw new Exception($"Error calling _client.GetAsync with {_settings.Uri}{_settings.MakeBaseUri}", ex.InnerException);
            }
```
Then I saw the exception:
        
<img width="596" alt="Screenshot 2022-09-10 163416" src="https://user-images.githubusercontent.com/10107978/189505266-62015fcc-4feb-43e8-ad62-5d55b1ffede1.png">

**Exception: Error calling _client.GetAsync with https://localhost:5021api/Makes**

There is no slash between the base url and the action!  Looking at my appsettings.development.json I realized that I needed to add a slash at the end of the variable: "Uri": "https://localhost:5021/"

Once I did that everything worked...  Sorry about this, and I hope I didn't ruin your weekend.

**Comment by skimedic** [comment]
not a problem. glad you figured it out.
