### ISSUE TITLE
Page 525 & 540 minor formatting issue

### ISSUE THREAD

**Issue by smcal** [Apress/pro-c-sharp-9-w-.net-core-5#2]
I don't see a printing number on the copyright page so I'm assuming I have the first printing.

On page 525 line 5 from top there is a newline missing after the colon -  `...function, shown here:static void`
Similar issue on 540 at the start of the code sample in section `Leveraging OS Verbs with ProcessStartInfo`

Found another on page 575 at the bottom of the page.  `...following code:private void cmdCancel_`
Page 586 3 lines above `"Fire-and-Forget" Void Async Methods"`  `...keyword as so:await`

**Comment by skimedic** [comment]
Thank you. I had already caught the first two that you mentioned. I've added the next two to the errata and confirmed the formatting is correct for the next edition.
