### ISSUE TITLE
GetHashCode() return unique values for anonymous types?

### ISSUE THREAD

**Issue by Ultrafeel** [Apress/pro-c-sharp-9-w-.net-core-5#3]
> Using this implementation of GetHashCode(), two anonymous types will yield the same hash value if (**and only if**) they have the same set of properties that have been assigned the same values.

Seems to be GetHashCode() cannot  return unique value for every set of values of every set of properties. So, the clause in parentheses is wrong, isn't it?

**Comment by skimedic** [comment]
No, this is correct. It's how hashing works.

**Comment by Ultrafeel** [comment]
So do You think 32 bit hash value can unambiguously represent each and every possible value of a set of properties with size more then 32 bit (information size, not memory footprint size)? Really? I think it contradicts information theory.

.Net can't hash this way. Here the proof: 
[csharp code gist](https://gist.github.com/Ultrafeel/6584d9d380cba56b109408ee18437a63)
Two instances of a same anonymous type, different values , same hashes.

Here Eric Lippert, developer of .Net :
> It does not provide a unique key for an object

[ericlippert.com](https://ericlippert.com/2011/02/28/guidelines-and-rules-for-gethashcode/)

**Comment by skimedic** [comment]
Oops, you're correct. Not sure where my head was. Funny, that sentence has been in just about every edition, you're the first person to catch that! Nice job.  I've updated the C# 10 version to remove the (and only if) part of the sentence.
