### ISSUE TITLE
OrderedEnumerable isn't returned by Where

### ISSUE THREAD

**Issue by Ultrafeel** [Apress/pro-c-sharp-9-w-.net-core-5#4]
`OrderedEnumerable` isn't returned by `Where` in a case, described by a quote below. `OrderedEnumerable` is returned by `OrderBy`. I've checked this in code. `OrderBy()` is an extension 
> The return value of the Where() method is hidden from view in this code example, but under the covers
you are operating on an OrderedEnumerable type. From this object, you call the generic OrderBy() method, which also requires a Func<> delegate parameter.

**Comment by skimedic** [comment]
You are correct. Code sample was refactored between editions, but missed the update in the text. I've corrected the type for the C# 10 edition. Thank you.
