### ISSUE TITLE
AutoLot Database Backup Files Not in Repository for Chapter 21

### ISSUE THREAD

**Issue by booberthecat** [Apress/pro-c-sharp-9-w-.net-core-5#5]
Hello -- In Chapter 21 under the heading, "Restoring the AutoLot Database Backup", two files (AutoLotWindows.ba_ and AutoLotDocker.ba_) are said to be stored in the chapter's files in the repository, but I am unable to find either one. In my case, I am primarily interested in the Windows file, but wanted to alert you to the absence of the Docker backup as well.

Please advise.

Thanks!

**Comment by skimedic** [comment]
I've re-added them. Apologies for the inconvenience.

**Comment by booberthecat** [comment]
No problem at all. Thanks for re-adding the files. Much appreciated.

Regards,

Kevin Meyers

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
